# Generated by Django 4.2.6 on 2025-05-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='直播标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='直播描述')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('scheduled_end_time', models.DateTimeField(verbose_name='计划结束时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('scheduled', '计划中'), ('live', '正在直播'), ('ended', '已结束'), ('cancelled', '已取消')], default='scheduled', max_length=15, verbose_name='状态')),
                ('stream_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='流密钥')),
                ('stream_url', models.URLField(blank=True, null=True, verbose_name='流地址')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream', to='courses.lesson', verbose_name='关联课时')),
            ],
            options={
                'verbose_name': '直播课程',
                'verbose_name_plural': '直播课程',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('file', models.FileField(upload_to='videos/', verbose_name='视频文件')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='缩略图')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='时长(秒)')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('ready', '就绪'), ('error', '错误')], default='processing', max_length=15, verbose_name='状态')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='是否可下载')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.lesson', verbose_name='关联课时')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='LiveStreamingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='在线时长(分钟)')),
                ('live_streaming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='videos.livestreaming', verbose_name='直播课')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_attendances', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '直播出席记录',
                'verbose_name_plural': '直播出席记录',
            },
        ),
        migrations.CreateModel(
            name='VideoWatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_duration', models.PositiveIntegerField(default=0, verbose_name='观看时长(秒)')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='上次位置(秒)')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('watch_date', models.DateTimeField(auto_now=True, verbose_name='观看日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频观看历史',
                'verbose_name_plural': '视频观看历史',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
