# Generated by Django 4.2.6 on 2025-05-05 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_courserating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='直播标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='直播描述')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='计划开始时间')),
                ('scheduled_end_time', models.DateTimeField(verbose_name='计划结束时间')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('scheduled', '未开始'), ('live', '直播中'), ('ended', '已结束'), ('canceled', '已取消')], default='scheduled', max_length=20, verbose_name='直播状态')),
                ('stream_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='推流密钥')),
                ('rtmp_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='RTMP推流地址')),
                ('play_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='播放地址')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='观看人数')),
                ('max_viewer_count', models.PositiveIntegerField(default=0, verbose_name='最高观看人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_events', to='courses.course', verbose_name='关联课程')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_events', to=settings.AUTH_USER_MODEL, verbose_name='讲师')),
            ],
            options={
                'verbose_name': '直播活动',
                'verbose_name_plural': '直播活动',
                'ordering': ['-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='LiveChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('live_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live.liveevent', verbose_name='直播活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '直播聊天',
                'verbose_name_plural': '直播聊天',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('attended', models.BooleanField(default=False, verbose_name='是否参与')),
                ('live_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='live.liveevent', verbose_name='直播活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '直播报名',
                'verbose_name_plural': '直播报名',
                'unique_together': {('user', 'live_event')},
            },
        ),
    ]
