# Generated by Django 4.2.6 on 2025-05-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='pre_recorded_video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='预录制视频URL'),
        ),
    ]
