# Generated by Django 4.2.6 on 2025-05-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL别名')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='封面图')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('learning_objectives', models.TextField(blank=True, null=True, verbose_name='学习目标')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name='预备知识')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=10, verbose_name='状态')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='价格')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='分类')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='讲师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '有效'), ('completed', '已完成'), ('expired', '已过期')], default='active', max_length=10, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '课程报名',
                'verbose_name_plural': '课程报名',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='章节描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课时标题')),
                ('lesson_type', models.CharField(choices=[('video', '视频'), ('document', '文档'), ('quiz', '测验')], default='video', max_length=10, verbose_name='课时类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='课时内容')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='时长(分钟)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='是否免费预览')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '课程课时',
                'verbose_name_plural': '课程课时',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', through='courses.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='not_started', max_length=15, verbose_name='状态')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='进度百分比')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='上次位置(秒)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.enrollment', verbose_name='报名记录')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='课时')),
            ],
            options={
                'verbose_name': '课时进度',
                'verbose_name_plural': '课时进度',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
