# Generated by Django 4.2.6 on 2025-05-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_video_url_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='课程视频URL'),
        ),
    ]
